import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import { GetMyInfo } from '../src/services/graphRequests';
import { IChat, IMe } from '../src/interfaces';
import { DateTime } from 'luxon';
import { toast, ToastContainer, ToastOptions } from 'react-toastify';
import LoginPage from '../src/pages/LoginPage';
import TeamsAppPage from '../src/pages/TeamsAppPage';
import 'react-toastify/dist/ReactToastify.css';

export default function Home() {

  const [token, setToken] = useState('');
  const [loading, setLoading] = useState(false);
  const [me, setMe] = useState<IMe>();

  const handleAlerts = (msg: any, type: 'default' | 'info' | 'success' | 'warning' | 'error' = 'default', timeMs: number = 10000) => {

    console.error(msg);

    let message = String(msg);
    if (msg?.response?.data?.error) message = `(${msg.response.data.error.code}) ${msg.response.data.error.message}`;

    const toastBody: ToastOptions = {
      position: "top-center",
      autoClose: timeMs,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "colored",
    }

    if (type === 'info') toast.info(message, toastBody);
    if (type === 'success') toast.success(message, toastBody);
    if (type === 'warning') toast.warning(message, toastBody);
    if (type === 'error') toast.error(message, toastBody);
    if (type === 'default') toast(message, toastBody);
  }

  const handleLogin = () => {
    if (!token) return
    setLoading(true)
    GetMyInfo(token)
      .then(resp => setMe(resp.data))
      .catch(e => handleAlerts(e, 'error'))
      .finally(() => setLoading(false))
  }

  const handleLogout = () => {
    if (window.confirm('Tem certeza que deseja sair?')) setMe(undefined);
  }


  return (
    <div>

      <Head>
        <title>Teams Quick Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="colored"
      />

      <main className={styles.main}>

        {!me ?
          <LoginPage
            token={token}
            loading={loading}
            handleLogin={handleLogin}
            handleAlerts={handleAlerts}
            setToken={setToken} />
          :
          <TeamsAppPage
            handleLogout={handleLogout}
            handleAlerts={handleAlerts}
            token={token}
            me={me} />}

      </main>

    </div>
  )

}

export function FriendlyDate({ date }: { date: DateTime; }): JSX.Element {
  const now = DateTime.now().setLocale('pt-BR');
  const dateTime = date.setLocale('pt-BR');
  const isDateHasSameMonth = date.hasSame(now, 'month');
  const friendlyDates = {
    tomorrow: `amanhã às ${dateTime.toFormat('HH:mm')}`,
    today: `hoje às ${dateTime.toFormat('HH:mm')}`,
    yesterday: `ontem às ${dateTime.toFormat('HH:mm')}`,
    week: `${dateTime.toFormat(`cccc (dd${isDateHasSameMonth ? '' : ' LLL'})`)} às ${dateTime.toFormat('HH:mm')}`,
    year: `${dateTime.toFormat('dd LLL')} às ${dateTime.toFormat('HH:mm')}`,
    fullDate: dateTime.toFormat('dd LLL yyyy HH:mm')
  };

  const Span = ({ children }: { children: any; }) => (
    <span title={dateTime.toFormat('dd/LL/yyyy HH:mm:ss')}>
      {children}
    </span>
  );

  if (dateTime.hasSame(now.plus({ days: 1 }), 'day'))
    return <Span>{friendlyDates.tomorrow}</Span>;

  if (dateTime.hasSame(now, 'day'))
    return <Span>{friendlyDates.today}</Span>;

  if (dateTime.hasSame(now.minus({ days: 1 }), 'day'))
    return <Span>{friendlyDates.yesterday}</Span>;

  if (dateTime.hasSame(now, 'week'))
    return <Span>{friendlyDates.week}</Span>;

  if (dateTime.hasSame(now, 'year'))
    return <Span>{friendlyDates.year}</Span>;

  return <Span>{friendlyDates.fullDate}</Span>;
}